"""Render Script Farm prompt templates from the REAL writer prompt builders.

The farm's cloud workers (ChatGPT via its GitHub tooling) must write drafts in
exactly the format WriterAgent._parse_draft consumes. Instead of hand-copying
prompt text into docs (which drifts), this renders the live system + generation
prompts per channel with {{PLACEHOLDER}} brief fields, and commits them under
scriptfarm/channels/<id>/. Re-run after any writer-prompt change:

    PYTHONPATH=src .venv/bin/python scripts/gen_scriptfarm_templates.py
"""

from __future__ import annotations

import asyncio
import json
from pathlib import Path

IMPL = Path(__file__).resolve().parents[1]
FARM = IMPL.parent / "scriptfarm"

SKIP = {"credentials"}


async def main() -> None:
    from omnicast.agents.writer import WriterAgent
    from omnicast.config.channel import ChannelProfileLoader
    from omnicast.config.niches import get_niche_config
    from omnicast.models.script import TopicBrief, TopicSource

    loader = ChannelProfileLoader(IMPL / "channels")
    writer = WriterAgent.__new__(WriterAgent)  # prompt builders only — no LLM

    channels = sorted(
        p.stem for p in (IMPL / "channels").glob("*.json") if p.stem not in SKIP
    )
    for channel_id in channels:
        try:
            channel = await loader.load(channel_id)
        except Exception as exc:  # non-pipeline channel files (e.g. reup configs)
            print(f"skipped {channel_id}: profile does not validate ({exc.__class__.__name__})")
            continue

        ncfg_key = (getattr(channel, "niche_config_key", "") or "").strip()
        if ncfg_key and "." in ncfg_key:
            nk, sk = ncfg_key.split(".", 1)
            niche_cfg = get_niche_config(nk, sk)
        elif ncfg_key:
            niche_cfg = get_niche_config(ncfg_key)
        else:
            niche_cfg = get_niche_config(channel.niche.value, channel.sub_niche)

        audience = channel.audience if isinstance(channel.audience, dict) else None
        channel_brand = {
            "brand_voice": getattr(channel, "brand_voice", "") or "",
            "tone": getattr(channel, "tone", "") or "",
            "hook_format": getattr(channel, "hook_format", "") or "",
            "voice_persona": getattr(channel, "voice_persona", "") or "",
        }
        system = writer._build_system_prompt(
            niche_cfg, audience=audience, channel_brand=channel_brand)

        brief = TopicBrief(
            title="{{TITLE}}",
            niche=channel.niche,
            market=channel.market,
            source=TopicSource.MANUAL,
            angle="{{CONTENT_ANGLE}}",
            key_points=["{{KEY_POINT_1}}", "{{KEY_POINT_2}}", "{{KEY_POINT_3}}"],
            target_duration_min=getattr(channel, "target_duration_min", 10) or 10,
            channel_id=channel_id,
            sub_niche=channel.sub_niche or "",
            target_audience="{{TARGET_AUDIENCE}}",
            pain_point="{{PAIN_POINT}}",
            content_angle="{{CONTENT_ANGLE}}",
            topics_done=["{{TOPICS_DONE}}"],
            next_topic="{{NEXT_TOPIC}}",
        )
        task = writer._build_generation_prompt(brief, "pain_hook", [], niche_cfg)

        out = FARM / "channels" / channel_id
        out.mkdir(parents=True, exist_ok=True)
        (out / "SYSTEM.md").write_text(
            "<!-- GENERATED by implementation/scripts/gen_scriptfarm_templates.py"
            " — do not hand-edit; re-run after writer prompt changes. -->\n\n"
            + system + "\n", encoding="utf-8")
        (out / "TASK.md").write_text(
            "<!-- GENERATED — replace every {{PLACEHOLDER}} with the queue item's"
            " fields before writing. -->\n\n" + task + "\n", encoding="utf-8")
        meta = {
            "channel_id": channel_id,
            "content_format": getattr(niche_cfg, "content_format", "explainer"),
            "target_duration_min": brief.target_duration_min,
            "niche": channel.niche.value,
            "market": channel.market.value,
        }
        (out / "meta.json").write_text(
            json.dumps(meta, indent=2) + "\n", encoding="utf-8")
        print(f"rendered {channel_id}: system={len(system)}ch task={len(task)}ch "
              f"format={meta['content_format']}")


asyncio.run(main())
